name: Node.js CI for PR

on:
  pull_request:
    branches: [ "spectroscopy" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: git submodule init
    - run: git submodule update
    - name: Install Ace dependencies
      run: npm install
      working-directory: ./modules/ace   
    - run: npm run build-all
    - run: mkdir -p ./_site && cp -r lib/ css/ fonts/ docs/ index.html help.html contact.html about.html LICENSE README.md server.js ./_site/